htpdate-0.9.0

diff --git a/htpdate.init b/htpdate.init
--- a/htpdate.init
+++ b/htpdate.init
@@ -1,40 +1,42 @@
 #!/bin/sh
 #
-# Minimal init script for htpdate
+# A minimal init script for htpdate
+
+test -x /usr/bin/htpdate || exit 0
 
 PIDFILE="/var/run/htpdate.pid"
-SERVERS="www.google.com www.yahoo.com www.linux.org www.freebsd.org"
+SERVERS="www.linux.org www.freebsd.org"
 
 # See how we were called.
 case "$1" in
-  start)
-	echo -n "Starting htpdate: "
-	# Set the time first before daemonizing, because the time offset
-	# might be too big for smooth time adjustment
-	/usr/bin/htpdate -s $SERVERS
-	/usr/bin/htpdate -D -i $PIDFILE $SERVERS
-	# or the above two lines combined in one
-	# /usr/bin/htpdate -D -s -i $PIDFILE $SERVERS
-	echo
-	;;
-  stop)
-	echo -n "Shutting down htpdate: "
-	if [ -f $PIDFILE ]
-	then
-		kill `cat $PIDFILE`
-	else
-		echo "$PIDFILE not found"
-	fi
-	echo
-	rm -f $PIDFILE
-	;;
-  restart)
-	$0 stop
-	$0 start
-	;;
-  *)
-	echo "Usage: $0 {start|stop|restart}"
-	exit 1
+	start)
+		echo "Starting HTTP Time Protocol daemon: htpdate"
+		# Set the time first before daemonizing, because the time offset
+		# might be too big for smooth time adjustment
+		/usr/bin/htpdate -s $SERVERS
+		/usr/bin/htpdate -D -i $PIDFILE $SERVERS
+		# or the above two lines combined in one
+		# /usr/bin/htpdate -D -s -i $PIDFILE $SERVERS
+		;;
+	stop)
+		echo "Stopping HTTP Time Protocol daemon: htpdate"
+		if [ -f $PIDFILE ]
+		then
+			kill `cat $PIDFILE`
+		else
+			echo "$PIDFILE not found"
+		fi
+		rm -f $PIDFILE
+		;;
+	restart)
+		$0 stop
+		$0 start
+		;;
+	*)
+		echo "Usage: $0 {start|stop|restart}"
+		exit 1
 esac
 
 exit 0
+
+# vi:set ts=4:
